### ISSUE TITLE
forced to create container div to render vNode Arrays

### ISSUE THREAD

**Issue by rz-robsn** [yelouafi/snabbdom-jsx#14]
Hi,

I'm working an app using Cyclejs, snabbom, and snabbdom-jsx. I found a weird behavior in my code. Basically the following code renders fine : 

```
        <div>
            <input type="text" />
            {
                <div className="clear-wrapper">
                    <span>clear</span>
                </div>
            }
            <a>Add</a>
        </div>
```

but if I put my "clear-wrapper" div in an array, like so :

```
        <div>
            <input type="text" />
            {
                [
                <div className="clear-wrapper">
                    <span>clear</span>
                </div>
                ]
            }
            <a>Add</a>
        </div>
```
 
then the "clear-wrapper" div is not included in the DOM, and is instead replaced by `undefined`:

```
         <div>
            <input type="text" />
            "undefined"
            <a>Add</a>
        </div>
```

**BUT** if I wrap the div array inside another div : 

```
        <div>
            <input type="text" />
            <div>
            {
                [
                <div className="clear-wrapper">
                    <span>clear</span>
                </div>
                ]
            }
            </div>
            <a>Add</a>
        </div>
```

Then the "clear-wrapper" div renders fine again. This is quite mind-boggling to me. 

I'm not sure if its a bug (it looks like one to me), but if it's expected behaviour, can someone point me to where that behaviour is documented ? I have been searching around and did not find anything. There is this [snabbdom issue](https://github.com/paldepind/snabbdom/issues/76) that I think talks about it, but I'm not sure that it does, as I am quite new to JSX and snabbdom. 

Is there a better solution other than the workaround I've found ? I'd like to avoid creating container divs just for that purpose if possible.

Thank you for your help and for this great library ! If you have any questions about my setup let me know.

**Comment by yelouafi** [comment]
can you check with the new version. issue with nested arrays is fixed

**Comment by rz-robsn** [comment]
I updated to version 0.3.1 and the bug does not appear anymore.

Thanks !
