### ISSUE TITLE
Not able to see simple SVG example

### ISSUE THREAD

**Issue by delaneyj** [yelouafi/snabbdom-jsx#6]
My attempt to [convert the simplest SVG example over to snabbdom-jsx](http://www.w3schools.com/svg/tryit.asp?filename=trysvg_myfirst) here

```jsx
<svg attrs={{width:100,height:100}}>
  <circle attrs={{cx:50,cy:50,r:40,stroke:"green",strokeWidth:4,fill:'yellow'}}/>
</svg>
```
Doesn't appear to be displaying anything but the generated actual dom does match the example.
```html
<svg width="100" height="100"><circle cx="50" cy="50" r="40" stroke="green" stroke-width="4" fill="yellow"></circle></svg>
```

Using Chrome and know SVG is working on the browser, have any ideas what I'm doing wrong?

**Comment by yelouafi** [comment]
did you follow the same approach as in the [svg example](https://github.com/yelouafi/snabbdom-jsx/tree/master/examples/svg) in the repo.
