### ISSUE TITLE
How to use this with TypeScript TSX?

### ISSUE THREAD

**Issue by eshansingh** [yelouafi/snabbdom-jsx#8]
It works wonders with Babel, but I'm having trouble plugging it into TypeScript. If you have any idea how I would really appreciate it!

Thanks!

**Comment by avesus** [comment]
`npm install --save snabbdom-jsx`

`tsc --jsx react`

In top of your *.tsx:
`/** @jsx html */`

Then
```
import { html } from 'snabbdom-jsx';
const React = {
  createElement: html
};```
